apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultservice
  name: resultservice
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultservice
  template:
    metadata:
      labels:
        app: resultservice
    spec:
      imagePullSecrets:
      - name: aws-registry-key
      containers:
      - name: resultservice
        image: 733141109198.dkr.ecr.eu-west-3.amazonaws.com/resultservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: resultservice
