apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voteservice
  name: voteservice
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voteservice
  template:
    metadata:
      labels:
        app: voteservice
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: voteservice
        ports:
        - containerPort: 80
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
      
