apiVersion: v1
kind: Service
metadata:
  labels:
    app: voteservice
  name: voteservice
  namespace: voteapp
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 80
  selector:
    app: voteservice
  
