apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workerservice
  name: workerservice
  namespace: voteapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workerservice
  template:
    metadata:
      labels:
        app: workerservice
    spec:
      imagePullSecrets:
      - name: aws-registry-key
      containers:
      - name: workerservice
        image: 733141109198.dkr.ecr.eu-west-3.amazonaws.com/workerservice:latest
        imagePullPolicy: Always
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_PORT
          value: "5432"
